language: csharp
dist: trusty

sudo: false  # use the new container-based Travis infrastructure

services:
  - postgres
  
env:
  - DB=pos
  
before_script:
  - psql -c 'create database postgres;' -U postgres
  
addons:
  postgresql: "9.4"

mono:
  - 5.0.1

os:
  - linux
  - osx
  
script:
  - ./build.sh All

branches:
  except:
  - gh-pages